### PR TITLE
How jesper stole Christmas

### PR DESCRIPTION
**Pull request by J35P312**
NO CHRISTMAS TREES, NO PRESENTS; NO NOTHING!

additional fixes:

Balanced variants (BND,INS,INV) larger than the maxbnd size (10 kb as default) are not printed

height of probes are not modified by *10.5

changed start and end positions

### CODE REVIEW

**Comment by dnil** [comment]
Just fix the travis... :-)

**Comment by J35P312** [comment]
Woopsiedaisy! I forgot to test on python3 =P. Now it should work!

**Comment by J35P312** [comment]
or not! maybe this is the problem Henrik is getting?

**Comment by dnil** [comment]
Puh! Nicely done. Ready for merge?

**Pull request merged**
