### PR TITLE
visualise probe height using snv vcf

### PR DESCRIPTION
**Pull request by J35P312**
The probe height is visualised using the probe height of the read coverage of snps found in input vcf file

The coverage tag of the info field is set to DP per default (GATK), but can be set to any value.

I have tested it, but I have not visualised the output cgh file, feel free to do so before accepting the pull request =P.

### CODE REVIEW

**Comment by dnil** [comment]
Cool! I'll meet up with JL next week reviewing loading of the current master. I'll try to check it then, or at least verify and release the current first before merging.. :)

**Comment by dnil** [comment]
Ahem, seems to fail build/test/review? Could you take a look at the rulings of our automatic overlords? Thanks!

**Comment by J35P312** [comment]
I had a look! 
I will clean up the code and remove the import numpy. The change xml module thingy seems a bit too much, I think that's an issue in it self.

Travis is treating vcf2cytosure as a ruby program, perhaps you could correct that?
Thank you too =P

**Comment by dnil** [comment]
Ahem, ok! Added a travis yaml - if you merge/add commit 6c8126e things might work! :)

**Comment by J35P312** [comment]
We seem to have though luck, perhaps we should write it in Ruby instead?=P

**Comment by dnil** [comment]
Ahem, now there is a very simple working test and travis config in master. Good luck rebasing.. 😝

**Comment by dnil** [comment]
Yay! Have you tried loading the resulting CGH as well?

**Comment by J35P312** [comment]
Not since  I did  the rebasing =P. I will have a look!

**Comment by J35P312** [comment]
Now I have tested it, it looks great!!
Merge it quickly! Before more  conflicts arise! =P

**Comment by dnil** [comment]
Phew, made it in time! ;) Sooo, anything else to release in 0.3.0 or should we snapshot it when its actually tested?

**Comment by J35P312** [comment]
Great! =P
Maybe we could add the select-sex-of-the-reference thingy? I think we could do it quickly!
Do we want to set the sex of the reference  manually? Or should it always match the patient?

**Pull request merged**
